name: wenznote
description: a note project
flutter_app_name:
  name: "温知笔记"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'nrenderParagraph.' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  synchronized: ^3.1.0
  # 设置剪切板内容时用到了
  rich_clipboard: ^1.0.1
  # 粘贴图片时用到了
  pasteboard: ^0.2.0
  uuid: ^3.0.7
  file: ^6.1.4
  path_provider: ^2.0.11
  image_size_getter: ^2.1.2
  flutter_screenutil: ^5.6.0
  image: ^3.1.3
  image_compression_flutter: ^1.0.2
  dio: ^4.0.6
  future_progress_dialog: ^0.2.1
  highlight: ^0.7.0
  flutter_code_editor: ^0.1.15
  url_launcher: ^6.1.7
  flutter_acrylic: ^1.0.0+2
  window_manager: ^0.3.0
  dart_json_mapper_flutter: ^2.0.1
  diff_match_patch: ^0.4.1
  sqflite: ^2.2.2
  path: ^1.8.2
  desktop_window: ^0.4.0
  octo_image: ^1.0.2
  archive: ^3.3.6
  super_drag_and_drop: ^0.3.0+2
  super_clipboard: ^0.3.0+2
  protobuf: ^2.1.0
  sqflite_common_ffi: ^2.2.3
  sqlite3_flutter_libs: ^0.5.13
  get: ^4.6.5
  fluent_ui: ^4.7.3
  flutter_fancy_tree_view: ^0.5.3+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dotted_border: ^2.0.0+1
  file_selector: ^0.9.3
  dart_markdown: ^3.1.6
  flutter_displaymode: ^0.6.0
  image_picker: ^0.8.7+5
  date_format: ^2.0.7
  fluttertoast: ^8.2.2
  vibration: ^1.7.7
  file_picker: ^5.2.10
  permission_handler: ^10.2.0
  flutter_tts: ^3.7.0
  external_path: ^1.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_html: ^2.2.1
  flutter_math_fork: ^0.5.0
  flutter_crdt:
    git: https://gitee.com/gdccj/flutter_crdt.git

  oktoast: ^3.3.1
  flutter_breadcrumb: ^1.0.1
  fl_chart: ^0.63.0
  desktop_multi_window: ^0.2.0
  device_info_plus: ^8.2.2
  easy_image_viewer: ^1.2.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.1
  json_diff: ^0.2.1
  encrypt: ^5.0.3
  web_socket_channel: ^2.4.0
  fixnum: ^1.1.0

  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.1
  image_cropper: ^5.0.1
  image_picker_windows: ^0.2.1+1
  crop_image: ^1.0.11
  image_cropping: ^0.0.13
  chinese_font_library: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1

dependency_overrides:
  watcher: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/note.svg
    - assets/images/calendar.svg
    - assets/images/outline.svg
    - assets/images/app_logo.png
    - assets/doc/help_windows.md
    - assets/osx-arc/
#  fonts:
#    - family: MiSans
#      fonts:
#        - asset: assets/fonts/MiSans-Normal.ttf